baseURL = 'https://www.dexterbosley.com/'
languageCode = 'en-us'
title = 'Thinking in Public'
theme = 'PaperMod'
publishDir = "docs"

[menus]

[[menus.main]]
  identifier = "all"
  name = "All"
  url = "/"
  weight = 10

[[menus.main]]
  identifier = "essays"
  name = "Essays"
  url = "/essays/"
  weight = 20

[[menus.main]]
  identifier = "stories"
  name = "Stories"
  url = "/stories/"
  weight = 30

[[menus.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 40
