
baseURL = 'https://www.dexterbosley.com/'
languageCode = 'en-us'
title = 'Thinking in Public'
theme = 'PaperMod'
publishDir = "docs"

[params]
  # This line tells the "All" tab to show these folders
  mainSections = ["essays", "stories"]

[params.assets]
    favicon = "/favicon.svg"
    favicon16x16 = "/favicon.svg"
    favicon32x32 = "/favicon.svg"
    apple_touch_icon = "/favicon.svg"

[menus]

[[menus.main]]
  identifier = "all"
  name = "All"
  url = "/"
  weight = 10

[[menus.main]]
  identifier = "essays"
  name = "Essays"
  url = "/essays/"
  weight = 20

[[menus.main]]
  identifier = "stories"
  name = "Stories"
  url = "/stories/"
  weight = 30

[[menus.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 40
paginate = 5
