baseURL = 'https://www.dexterbosley.com/'
languageCode = 'en-us'
title = 'Dexter Bosley'
publishDir = "docs"
disableKinds = ["section", "taxonomy", "term"]

[pagination]
  pagerSize = 10

[params]
  mainSections = ["essays", "stories", "notes"]

[markup.goldmark.renderer]
  unsafe = true
